Move all procedures into functions
- Setup main function for main routine calling

diff --git a/host-switch b/host-switch
--- a/host-switch
+++ b/host-switch
@@ -252,62 +252,67 @@ shell_input()
 # main routine
 #################################
 
+main()
+{
+    # initialize
+    if [ "$1" = '-h' -o "$1" = '--help' -o "$1" = 'help' ]; then
+	Usage 0
+    else
+	look_up_group 0
+    fi
+
+    # list/show operation
+    if [ "$1" = '' ]; then
+	print_out_setting
+	exit 0
+    elif [ "$1" = 'show' -o "$1" = 'list' ]; then
+	if [ "$2" = '' ]; then
+	    print_out_setting
+	    exit 0
+	else
+	    print_out_test_set $2
+	    exit 0
+	fi
+    elif [ "$1" != 'all-off' -a "$1" != 'on' -a "$1" != 'shell' ]; then
+	Usage 1
+    else
+	check_root
+    fi
+
+    # The process should have "$1" when they come to here.
+    # options:
+    #   all-off     use default external DNS record
+    #   shell       interactive selection
+    #   on xxx	switch on xxx, and turn off any other records
+
+    if [ "$1" = "all-off" ]; then
+	switch_all_off ""
+	echo "Use global DNS setting now"
+    elif [ "$1" = "on" ]; then
+	# we need to parse "$2" here, to see if its a valid record name in the $HOSTS file
+	if [ -z "$2" ]; then
+	    error "Please provide group name"
+	    exit 1
+	fi
+	if ! in_list 'groups' "$2" ; then
+	    error "Not a valid group name"
+	    exit 1
+	fi
+	switch_all_off "$2"
+	switch_on "$2" 1
+    elif [ "$1" = "shell" ]; then
+	# interactive mode
+	shell_input
+    else
+	# should not go here
+	error "Fatal error"
+	exit 1
+    fi
+}
+
+
 # global variables
 sets=""
 groups=""
 
-# initialize
-if [ "$1" = '-h' -o "$1" = '--help' -o "$1" = 'help' ]; then
-    Usage 0
-else
-    look_up_group 0
-fi
-
-# list/show operation
-if [ "$1" = '' ]; then
-    print_out_setting
-    exit 0
-elif [ "$1" = 'show' -o "$1" = 'list' ]; then
-    if [ "$2" = '' ]; then
-	print_out_setting
-	exit 0
-    else
-	print_out_test_set $2
-	exit 0
-    fi
-elif [ "$1" != 'all-off' -a "$1" != 'on' -a "$1" != 'shell' ]; then
-    Usage 1
-else
-#    check_root
-    printf ""
-fi
-
-# The process should have "$1" when they come to here.
-# options:
-#   all-off     use default external DNS record
-#   shell       interactive selection
-#   on xxx	switch on xxx, and turn off any other records
-
-if [ "$1" = "all-off" ]; then
-    switch_all_off ""
-    echo "Use global DNS setting now"
-elif [ "$1" = "on" ]; then
-    # we need to parse "$2" here, to see if its a valid record name in the $HOSTS file
-    if [ -z "$2" ]; then
-	error "Please provide group name"
-	exit 1
-    fi
-    if ! in_list 'groups' "$2" ; then
-	error "Not a valid group name"
-	exit 1
-    fi
-    switch_all_off "$2"
-    switch_on "$2" 1
-elif [ "$1" = "shell" ]; then
-    # interactive mode
-    shell_input
-else
-    # should not go here
-    error "Fatal error"
-    exit 1
-fi
+main $@
